services:
  pg-database:
    image: postgres:13
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=ny_taxi
    volumes:
      - "ny_taxi_postgres_data_volume:/var/lib/postgresql/data:rw"
    ports:
      - "5432:5432"
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - "8080:80"
volumes:
  ny_taxi_postgres_data_volume:
    external: true

#docker volume create ny_taxi_postgres_data_volume

#docker network create pg-network
#

# STEP 1: TO RUN POSTGRES SERVER
#docker run -it \
#  -e POSTGRES_USER="root" \
#  -e POSTGRES_PASSWORD="root" \
#  -e POSTGRES_DB="ny_taxi" \
#  -v ny_taxi_postgres_data_volume:/var/lib/postgresql/data \
#  -p 5432:5432 \
##  --network=pg-network \
##  --name pg-database \
#  postgres:13

# OPTIONAL: TO RUN PGADMIN INTERACTIVELY
# docker run -it \
#  -e PGADMIN_DEFAULT_EMAIL="admin@admin.com" \
#  -e PGADMIN_DEFAULT_PASSWORD="root" \
#  -p 8080:80 \
#  --network=pg-network \
#  --name pg-admin \
#  dpage/pgadmin4


# pgcli -h 172.31.227.86 -u root -d ny_taxi
# pgcli -h localhost -u root -d ny_taxi
#

# STEP 2: INGEST DATA TO SQL DATABASE IN VOLUME
#url="https://github.com/DataTalksClub/nyc-tlc-data/releases/download/yellow/yellow_tripdata_2021-01.csv.gz"
#
#python ingest_data.py \
#  --user=root \
#  --password=root \
#  --host=172.31.227.86 \
#  --port=5432 \
#  --db=ny_taxi \
#  --table_name=yellow_taxi_trips \
#  --url=${url}

# STEP 3: BUILD DOCKER CONTAINER
# docker build -t taxi_ingest:v001 .
#
# STEP 4: RUN DOCKER WORKFLOW
#URL="https://github.com/DataTalksClub/nyc-tlc-data/releases/download/yellow/yellow_tripdata_2021-01.csv.gz"
#
#docker run -it \
#  --network=pg-network \
#  taxi_ingest:v001 \
#    --user=root \
#    --password=root \
#    --host=pg-database \
#    --port=5432 \
#    --db=ny_taxi \
#    --table_name=yellow_taxi_trips \
#    --url=${URL}